name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set some helpers commands
        id: util
        run: |
          echo "::set-output name=set_env::cmake\ -P\ ${{ github.workspace }}/set_env.cmake\ --"
          echo "::set-output name=add_path::cmake\ -P\ ${{ github.workspace }}/add_path.cmake\ --"

      - name: Add some environment vars
        run: |
          ${{ steps.util.outputs.add_path }} "${{ github.workspace }}" "/test/dir"
          ${{ steps.util.outputs.set_env }} TEST_VAR="Hello" OTHER_VAR="World"
          
      - name: Echo result on windows
        if: ${{ matrix.os }} == 'windows-latest'
        run: |
          echo "Environment:"
          echo "TEST_VAR: %TEST_VAR%"
          echo "OTHER_VAR: %OTHER_VAR%"
          echo ""
          echo "Path:"
          echo %PATH%
      
      - name: Echo result on linux/macos
        if: ${{ matrix.os }} != 'windows-latest'
        run: |
          echo "Environment:"
          echo "TEST_VAR: $TEST_VAR"
          echo "OTHER_VAR: $OTHER_VAR"
          echo ""
          echo "Path:"
          echo $PATH
