name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set some helpers commands
        id: util
        run: |
          echo "::set-output set-env='cmake -P ${{ github.workspace }}/set-env.cmake --'"
          echo "::set-output add-path:='cmake -P ${{ github.workspace }}/add-path.cmake --'"

      - name: Add some environment vars
        run: |
          ${{ steps.util.outputs.set-env }} TEST_VAR="Hello" OTHER_VAR="World"
          ${{ steps.util.outputs.add-path }} "${{ github.workspace }}" "/test/dir"

      - name: Echo result on windows
        if: ${{ matrix.os }} == 'windows-latest'
        run: |
          echo "Environment:"
          echo "TEST_VAR: %TEST_VAR%"
          echo "OTHER_VAR: %OTHER_VAR%"
          echo ""
          echo "Path:"
          echo %PATH%
      
      - name: Echo result on linux/macos
        if: ${{ matrix.os }} != 'windows-latest'
        run: |
          echo "Environment:"
          echo "TEST_VAR: $TEST_VAR"
          echo "OTHER_VAR: $OTHER_VAR"
          echo ""
          echo "Path:"
          echo $PATH
